### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Amin Klein",
  "email": "amin@gmail.com",
  "address": "Ibrahimova 152",
  "dateOfBirth": "2007-03-23",
  "registeredDate": "2026-04-30"
}
###